#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export EDITOR='subl'

bg() {
  "$@" &
}

#
# aliasses
#

alias mci='mvn clean install'
alias mst='mvn clean install -Dmaven.test.skip=true'
alias gk='gitk &'
alias gg='git gui &'
alias gs='git status -sb'
alias gsr='git svn rebase'
alias gsd='git svn dcommit'

alias spull='git stash -u && gsr && git stash apply'
alias spush='git stash -u && gsd && git stash apply'

#
# default apps
#

alias -s {pdf}="bg o"
alias -s {md,txt,conf,properties,scala,java,js}="subl -n"

alias -s htm="$BROWSER"
alias -s html="$BROWSER"
alias -s jar="java -jar"
alias -s deb="sudo dpkg -i"

alias -g g='|grep '