#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export JMSLOGDIR='/tmp/jms-journal'
export EDITOR='subl'
export BROWSER='chrome'

export SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxMetaspaceSize=1024M"
export DDD_LEAVEN_AKKA_HOME="/home/newion/Projects/ddd-leaven-akka-v2"
export IDEA_HOME="/opt/devel/idea"

export JENKINS_HEDVENTURES_USER="newion"
export JENKINS_HEDVENTURES_PSWD="7biOBDk2LFgs" 

bg() {
  "$@" &
}

#
# default apps
#

alias -s {pdf}="bg o"
alias -s {md,txt,conf,properties,scala,java,js}="subl -n"

alias -s htm="$BROWSER"
alias -s html="$BROWSER"
alias -s jar="java -jar"
alias -s deb="sudo dpkg -i"

alias -g g='|grep '
alias -g s='subl -n'
alias -g ki='sudo kill -9'

#
# aliasses
#

alias mci='mvn clean install'
alias mst='mvn clean install -Dmaven.test.skip=true'
alias gk='gitk &'
alias gg='git gui &'
alias gs='git status -sb'
alias gsr='git svn rebase'
alias gsd='git svn dcommit'
alias gss='git submodule status'

alias spull='git stash -u && gsr && git stash apply'
alias spush='git stash -u && gsd && git stash apply'

alias acup='cd ~/Projects/acavista; mr up; cd -'
alias acst='cd ~/Projects/acavista; mr st; cd -'
alias acdi='cd ~/Projects/acavista; mr di; cd -'
alias update='sudo apt-get dist-upgrade'

alias release='sbt "release with-defaults"'
alias sbt="sbt -mem 1500"

alias rmvn="mvn -s ~/.m2/settings-rewe4.xml"

findgrep() { find . -type f -exec grep --colour -nHr "$1" {} \; ; }
